In [2]:
# zip() function in Python combines multiple iterables into a single iterator of tuple.

names = ['John','Smith','Alex','Tina']
marks = [85,90,82,93]

finalInfo = zip(names,marks)
print(list(finalInfo))

[('John', 85), ('Smith', 90), ('Alex', 82), ('Tina', 93)]


In [3]:
finalInfo = [('John', 85), ('Smith', 90), ('Alex', 82), ('Tina', 93)]
# for unzipping use *operator
names , marks = zip(*finalInfo)
print(names)
print(marks)

('John', 'Smith', 'Alex', 'Tina')
(85, 90, 82, 93)


In [4]:
names = ['John','Smith','Alex','Tina']
marks = [85,90,82,93]

for i in range(len(names)):   # range(4) 0 1 2 3
    print(names[i] , marks[i])

John 85
Smith 90
Alex 82
Tina 93


In [5]:
names = ['John','Smith','Alex','Tina']
marks = [85,90,82,93]

for n , m in zip(names,marks):
    print(n,m)

John 85
Smith 90
Alex 82
Tina 93


In [6]:
# Comprehensions In Python
# it provides you a concise and short way to construct new sequences

# List Comprehensions
# generate an even list 
numbers = [3,4,6,7,8,9,10,11,15,16,18,21,22,26]
list1 = []
for i in numbers:
    if i%2==0:
        list1.append(i)
print(list1)

[4, 6, 8, 10, 16, 18, 22, 26]


In [7]:
numbers = [3,4,6,7,8,9,10,11,15,16,18,21,22,26]
# output_list = [output_expression for i in sequence if expression]
list1 = [i for i in numbers if i%2==0]
print(list1)

[4, 6, 8, 10, 16, 18, 22, 26]


In [8]:
numbers = [3,4,6,7,8,9,10]
list1 = [i**2 for i in numbers]
print(list1)

[9, 16, 36, 49, 64, 81, 100]


In [9]:
# Nested for loop Using List comprehension
str1 = 'abc'
str2 = 'def'
for i in str1:
    for j in str2:
        print(i,j)

a d
a e
a f
b d
b e
b f
c d
c e
c f


In [10]:

list1 = [i+' '+j for i in str1 for j in str2]
print(list1)


['a d', 'a e', 'a f', 'b d', 'b e', 'b f', 'c d', 'c e', 'c f']


In [11]:
# Dictionary Comprehension
names = ['John','Smith','Alex','Tina']
marks = [85,90,82,93]

stInfo = {}
for (k,v) in zip(names,marks):
    stInfo[k] = v

print(stInfo)

{'John': 85, 'Smith': 90, 'Alex': 82, 'Tina': 93}


In [12]:
names = ['John','Smith','Alex','Tina']
marks = [85,90,82,93]
stInfo = {k:v for (k,v) in zip(names,marks)}
print(stInfo)


{'John': 85, 'Smith': 90, 'Alex': 82, 'Tina': 93}


In [13]:
numbers = [1,2,3,4,5]
cubes = {}
for i in numbers:
    cubes[i] = i**3
print(cubes)


{1: 1, 2: 8, 3: 27, 4: 64, 5: 125}


In [14]:
numbers = [1,2,3,4,5]
cubes = {i:i**3 for i in numbers}
print(cubes)

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125}


In [15]:
# Set Comprehension
numbers = [1,2,3,4,4,5,5,6,7,7,8,8,9,10,10,10,9,3,5]
cubes = {i:i**3 for i in numbers}
print(cubes)

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}


In [16]:
numbers = [1,2,3,4,4,5,5,6,7,7,8,8,9,10,10,10,9,3,5]
cubes = {i:i**3 for i in numbers if i%2==0}
print(cubes)

{2: 8, 4: 64, 6: 216, 8: 512, 10: 1000}


In [17]:
numbers = [1,2,3,4,4,5,5,6,7,7,8,8,9,10,10,10,9,3,5]
set1 = {i for i in numbers if i%2==0}
print(set1)

{2, 4, 6, 8, 10}


In [18]:
# Generator comprehension
# is similar like list comprehension with one diff 
#       --> Generator comprehension use circular brackets
#       --> it is more memory efficient
numbers = [1,2,3,4,4,5,5,6,7,7,8,8,9,10,10,10,9,3,5]
res = (i for i in numbers if i%2==0)
print(res)

for i in res:
    print(i,end=' ')

<generator object <genexpr> at 0x0000015FDE099150>
2 4 4 6 8 8 10 10 10 

In [19]:
# enumerate()
# it adds a counter to an iterable
# it allows you to keep track of the number of iterations
list1 = [1,2,3,4,5,6,7,8,9,10]
for i in enumerate(list1):
    print(i)

(0, 1)
(1, 2)
(2, 3)
(3, 4)
(4, 5)
(5, 6)
(6, 7)
(7, 8)
(8, 9)
(9, 10)


In [20]:
import numpy
print(numpy.__version__)


2.2.2


In [21]:
!pip install numpy --upgrade

In [22]:
import numpy
print(numpy.__version__)

2.2.2


In [23]:
# Data Science
# Numpy Part - 1

# What is data science?
# Data science is the study of data to extract meaningful insights for business. 
# It is a multidisciplinary approach that combines principles and practices from the 
# fields of mathematics, statistics, artificial intelligence, and computer engineering 
# to analyze large amounts of data. This analysis helps data scientists to ask and answer questions
# like what happened, why it happened, what will happen, and what can be done with the results.


# Data Science is about data gathering, analysis and decision-making.

# Data Science is about finding patterns in data, through analysis, and make future predictions.

# By using Data Science, companies are able to make:
#    Better decisions (should we choose A or B)
#    Predictive analysis (what will happen next?)
#    Pattern discoveries (find pattern, or maybe hidden information in the data)

# Where is Data Science Needed?

# Data Science is used in many industries in the world today, e.g. banking,
# consultancy, healthcare, and manufacturing.

In [24]:
# Numpy

# NumPy is a Python library used for working with arrays.

# It also has functions for working in domain of linear algebra, fourier transform,
# and matrices.

# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you
# can use it freely.

# NumPy stands for Numerical Python.


In [25]:
import numpy as np

In [26]:
# array() --> used to create 1D or 2D array
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [27]:
# Numpy vs List
list1 = [10,20,30,40,50]
print(list1)

# multiply each element by 2
print(list1*2)
for i in list1:
    print(i*2)

[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
20
40
60
80
100


In [28]:
arr = np.array([10,20,30,40,50])
print(arr*2)

[ 20  40  60  80 100]


In [29]:
# array is a collection of similar data type
arr = np.array([10,20.21,'Python',True])
print(arr)

['10' '20.21' 'Python' 'True']


In [30]:
# numpy array()
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [31]:
# shape property
# used to determine the dimensions of an array

# for 1D array shape returns (n,)
# where n is the number of elements

# for 2D array shape returns (n,m)
# where n is the number of rows and m is the number of columns

print(arr.shape)

(5,)


In [32]:
# Indexing and Slicing
arr = np.array([10,20,30,40,50])

# 10 20 30 40 50
# 0  1   2  3  4
# -5 -4 -3 -2 -1

print(arr[3])
print(arr[-1])
print(arr[1:4])

print(arr[::-1])


40
50
[20 30 40]
[50 40 30 20 10]


In [33]:
# 2D Array
twod = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twod)
print(twod.shape)

x = np.array([[1,2,3],[4,5,6]])
print(x.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(2, 3)


In [34]:
# indexing in 2D Array
twod = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twod)
print(twod[0,2])

# print second row
print(twod[1,:])

# print third column
print(twod[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[4 5 6]
[3 6 9]


In [35]:
# dtype property
# used to determine the data type of an array

arr = np.array([10,20,30,40,50])
print(arr.dtype)
print(arr.itemsize,'Bytes')   # returns memory size of  array elements

# int32 : memory size of one array element in BITS  [4 Bytes] 

arr = np.array([10,20,30,40,50],dtype='i2')
print(arr.itemsize,'Bytes')  # 2bytes --> 16 digits

arr = np.array([10,20,30,40,50],dtype='i1')
print(arr.itemsize,'Bytes')  # 1bytes --> 8 digits

int64
8 Bytes
2 Bytes
1 Bytes


In [36]:
# copy() vs view()

# in copy() if you make any changes in org array , it won't effect the copied array
# if you make any changes in copied array , it won't effect the org array

org_arr = np.array([10,20,30,40])
print(org_arr)

copied_arr = org_arr.copy()
print(copied_arr)

copied_arr[0] = 100
print(copied_arr)
print(org_arr)

[10 20 30 40]
[10 20 30 40]
[100  20  30  40]
[10 20 30 40]


In [37]:
# view()
# in view() if you make any changes in org array , it will effect the copied array
# if you make any changes in copied array , it will effect the org array

org_arr = np.array([10,20,30,40])
print(org_arr)

copied_arr = org_arr.view()
print(copied_arr)

copied_arr[0] = 100
print(copied_arr)
print(org_arr)

[10 20 30 40]
[10 20 30 40]
[100  20  30  40]
[100  20  30  40]


In [38]:
# reshape() : used to change the dimensions of an array

# convert 1D into 2D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)   # 12  -->   2x6  6x2  3x4  4x3  12x1  1x12

arr = arr.reshape(4,3)
print(arr)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
# convert 2D into 1D

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)

arr = arr.reshape(9)
print(arr)

(3, 3)
[1 2 3 4 5 6 7 8 9]


In [40]:
# another way to convert 2D into 1D

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr = arr.reshape(-1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [41]:
# another way to convert 2D into 1D
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr = arr.flatten()
print(arr)

[1 2 3 4 5 6 7 8 9]


In [42]:
# Filter an array
arr = np.array([23,7,3,6,2,54,1,67])
op = arr%2==0
print(op)  # BOOLEAN MASKING
print(arr[op])

[False False False  True  True  True False False]
[ 6  2 54]


In [43]:
arr = np.array([4,7,3,6,2,5,4,1,8,9,5,3,2])
res = arr > 5
print(arr[res])

[7 6 8 9]


In [44]:
arr = np.array([23,7,3,6,2,54,1,67])
res = (arr>2) & (arr<27)
print(arr[res])


[23  7  3  6]


In [45]:
# Modify element using boolean indexing
arr = np.array([12,3,4,5,32,67,52,25,50])
arr[arr%2==0] = 0
print(arr)

[ 0  3  0  5  0 67  0 25  0]


In [46]:
# where()  --> used to return index numbers in an output
arr = np.array([1,4,2,7,8,3,9,10,2,4])
res = np.where(arr>5)
print(res)
print(arr[res])

(array([3, 4, 6, 7]),)
[ 7  8  9 10]


In [47]:
# concatenate()
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [48]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12],[13,14,15]])
arr = np.concatenate((arr1,arr2))
print(arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [49]:

# array_split(arrayName,splitValue)
arr = np.array([1,2,3,4,5,6,7,8])
arr = np.array_split(arr,3)
print(arr)


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [50]:
# sorting of an array
# sort()

arr = np.array([1,4,2,7,9,3,5,8,6,10])
print(np.sort(arr))   # by default it will sort in ascending order

[ 1  2  3  4  5  6  7  8  9 10]


In [51]:
arr = np.array([1,4,2,7,9,3,5,8,6,10])
print(np.sort(arr)[::-1]) # descending order

[10  9  8  7  6  5  4  3  2  1]


In [52]:

# zeros()  ones()  full()  sum()

# zeros() it is used fill an array filled with 0's
# default data type will be float

# 1d
arr = np.zeros(6)
print(arr)


[0. 0. 0. 0. 0. 0.]


In [53]:
arr = np.zeros(6,dtype='i')
print(arr)

[0 0 0 0 0 0]


In [54]:
arr = np.zeros((3,3),dtype='i')
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [55]:
# ones() it is used fill an array filled with 1's
# default data type will be float

arr = np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [56]:
# full(size,constantValue)
# used to fill an array with a constant value

x = np.full(9,121)
print(x)


[121 121 121 121 121 121 121 121 121]


In [57]:
x = np.full((3,4),26)
print(x)


[[26 26 26 26]
 [26 26 26 26]
 [26 26 26 26]]


In [58]:

# sum()
print(x.sum())

312


In [59]:
# Numpy Random Module
from numpy import random
x = random.randint(100)
print(x)


92


In [60]:
x = random.randint(120,150)
print(x)

143


In [61]:
# rand() method generate a random float value b/w 0 and 1
x = random.rand()
print(x)

0.5803700352741956


In [62]:
# 1D
x = random.randint(100,size=(8))
print(x)


[76 25 43 74 15 59 29 52]


In [63]:

# 2D
x = random.randint(20,40,(4,5))
print(x)


[[20 34 29 20 27]
 [20 26 36 20 28]
 [36 30 27 28 22]
 [33 24 35 33 24]]


In [64]:
# 1D
x = random.rand(10)
print(x)


[0.67523176 0.98452492 0.23605342 0.67463642 0.58373807 0.55233772
 0.40566089 0.92262212 0.61718359 0.80059572]


In [65]:
# 2D
x = random.rand(5,6)
print(x)


[[0.77296627 0.35827698 0.14684398 0.47858463 0.44514625 0.89261804]
 [0.88949033 0.57117867 0.81933113 0.59510731 0.33215136 0.12828547]
 [0.81286193 0.80140148 0.45750567 0.8922765  0.36137985 0.61235686]
 [0.18328423 0.6072665  0.12908862 0.26547737 0.20420737 0.77992408]
 [0.77230252 0.91884709 0.9219632  0.6657307  0.69103634 0.81351241]]


In [66]:
# numpy arange()
# it is used to generate a sequence of integer values

# arange(x)
# it is used to generate a sequence of integer values starting from zero till x-1
print(np.arange(11))

# arange(x,y)
# it is used to generate a sequence of integer values starting from x till y-1
print(np.arange(20,40))

# arange(x,y,stepCount)
# it is used to generate a sequence of integer values starting from x till y-1
print(np.arange(20,40,2))


[ 0  1  2  3  4  5  6  7  8  9 10]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[20 22 24 26 28 30 32 34 36 38]


In [67]:
# Numpy Broadcasting
arr1 = np.array([3,4,5])
arr2 = np.array([7,6,9])
print(arr1+arr2)

[10 10 14]


In [69]:
arr1 = np.array([3,4,5])
arr2 = np.array([7])
print(arr1*arr2)

[21 28 35]
